# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  schedule:
    - cron: 0 4 1 * *

permissions:
  contents: write
  packages: write

jobs:
  run_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t blog:latest .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker tag blog:latest ghcr.io/${{ github.repository_owner }}/blog:latest
          docker push ghcr.io/${{ github.repository_owner }}/blog:latest

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 46.101.95.175
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yaml"
          target: "/root/"

      - name: Pull latest Docker image and run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 46.101.95.175
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            export CERT_PATH="${{ secrets.CERT_PATH }}"
            export KEY_PATH="${{ secrets.KEY_PATH }}"
            export ENV="production"
            export TURSO_DATABASE="${{ secrets.TURSO_DATABASE }}"
            docker compose pull
            docker image prune -a -f
            docker compose down
            docker compose up -d
